version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3000

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nextjs
    restart: always
    networks:
      - app-network
    command: >
      sh -c "apk add --no-cache certbot &&
             certbot certonly --standalone --non-interactive --agree-tos --email x571839175@gmail.com -d yikai.global -d www.yikai.global &&
             nginx -g 'daemon off;'"

networks:
  app-network:
    driver: bridge
